"""empty message

Revision ID: 0a2e92490a90
Revises: 2664b57b2b67
Create Date: 2025-01-08 14:28:37.254873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2e92490a90'
down_revision = '2664b57b2b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.Integer(), nullable=False))
        batch_op.drop_column('paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('pid')

    # ### end Alembic commands ###
