"""empty message

Revision ID: 2664b57b2b67
Revises: 706b95479133
Create Date: 2025-01-08 12:17:15.786883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2664b57b2b67'
down_revision = '706b95479133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
